name: TeleportBow
version: ${project.version}
main: me.xyrophyte.teleportbow.TeleportBow
api-version: 1.17
authors: [ XyroPhyte ]
description: A simple Teleportation Bow Spigot plugin.
website: https://sites.google.com/view/xyrophyte/
commands:
  tpbow:
    description: Gives the player a Teleportation Bow and an Arrow.
    usage: /tpbow
